### ISSUE TITLE
Unable to run on CentOS

### ISSUE THREAD

**Issue by emerysteele** [clarkx86/papyrusjs#21]
`[mcbserver@c ~]$ ./papyrus --world="./serverfiles/worlds/Bedrock level" --textures="./Vanilla_Resource_Pack" --output="./worldmap" --mode="topdown_shaded" --force-download
papyrus.js v1.0.5a by clarkx86
Threads: 4
Texture directory is missing or --force-download has been specified. Downloading...
/home/mcbserver/Vanilla_Resource_Pack/textures.tmp.zip
[=================================] 100%DownloadDownloading...2846205813/ 46205813
Extracting...
(node:29866) UnhandledPromiseRejectionWarning: Error: Failed to open database
    at MinecraftLevelDOWN._open (/snapshot/papyrusjs/node_modules/leveldb-mcpe/index.js:39:19)
    at MinecraftLevelDOWN.AbstractLevelDOWN.open (/snapshot/papyrusjs/node_modules/abstract-leveldown/abstract-leveldown.js:36:10)
    at DeferredLevelDOWN._open (/snapshot/papyrusjs/node_modules/deferred-leveldown/deferred-leveldown.js:19:12)
    at DeferredLevelDOWN.AbstractLevelDOWN.open (/snapshot/papyrusjs/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:8)
    at LevelUP.open (/snapshot/papyrusjs/node_modules/levelup/lib/levelup.js:89:11)
    at new LevelUP (/snapshot/papyrusjs/node_modules/levelup/lib/levelup.js:61:8)
    at LevelUP (/snapshot/papyrusjs/node_modules/levelup/lib/levelup.js:33:12)
    at init (/snapshot/papyrusjs/app.js:0:0)
    at Promise.then (/snapshot/papyrusjs/app.js:0:0)
(node:29866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by clvrk** [comment]
Hey @emerysteele! Thanks four your report!
Can you attach your Minecraft world so I can investiage this further :)?

Thank you and have a good start into the week :-)!

**Comment by emerysteele** [comment]
[http://yams.playified.ca/Bedrock level.zip](http://yams.playified.ca/Bedrock level.zip)

**Comment by emerysteele** [comment]
http://yams.playified.ca/Bedrock%20level.zip

**Comment by Nodman** [comment]
Getting the same output on on _Ubuntu 18.04.4_. if executing with prebuilt binary:

`./papyrus --world="./1.14.30.2/worlds/Goodtimes/" --output="./map"`

`papyrus.js v1.0.5a by clarkx86
Threads: 6
(node:850) UnhandledPromiseRejectionWarning: Error: Failed to open database
    at MinecraftLevelDOWN._open (/snapshot/papyrusjs/node_modules/leveldb-mcpe/index.js:39:19)
    at MinecraftLevelDOWN.AbstractLevelDOWN.open (/snapshot/papyrusjs/node_modules/abstract-leveldown/abstract-leveldown.js:36:10)
    at DeferredLevelDOWN._open (/snapshot/papyrusjs/node_modules/deferred-leveldown/deferred-leveldown.js:19:12)
    at DeferredLevelDOWN.AbstractLevelDOWN.open (/snapshot/papyrusjs/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:8)
    at LevelUP.open (/snapshot/papyrusjs/node_modules/levelup/lib/levelup.js:89:11)
    at new LevelUP (/snapshot/papyrusjs/node_modules/levelup/lib/levelup.js:61:8)
    at LevelUP (/snapshot/papyrusjs/node_modules/levelup/lib/levelup.js:33:12)
    at init (/snapshot/papyrusjs/app.js:0:0)
    at Promise.then (/snapshot/papyrusjs/app.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Also I was bale to run everything successfully once with not prebuilt binaries, but every next time I am getting error:

`node ./ --world="../1.14.30.2/worlds/Goodtimes/" --output="../map"`

`papyrus.js v1.1.0a by clarkx86 and contributors
Threads: 6
Attempting to open database...
[1]    900 segmentation fault (core dumped)  node ./ --world="../1.14.30.2/worlds/Goodtimes/" --output="../map"
`

**Comment by clvrk** [comment]
The issue seems to be resolved with the latest changes in [`master`](https://github.com/clarkx86/papyrusjs/tree/4c5a7800d33a3a5a77ed577e9d5d449c84f9bdeb) and I was able to successfully render @emerysteele's map.
I will release a new build in the following hours.

Thanks for reporting! If you find any more bugs or have any issue with the new release, please let me know :-)!

**Comment by clvrk** [comment]
[`v1.1.0-alpha`](https://github.com/clarkx86/papyrusjs/releases/tag/v1.1.0-alpha) just released!
Please let me know if this has resolved the issue! Thanks :-)

**Comment by emerysteele** [comment]
1.1.0 did seem to resolve that issue.

But now after update the minecraft server to version 1.14.32, there is a new error. Maybe I should make a new issue? This is the output:
`ror: Cannot read property 'stone' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:2832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[--------------------------------] 0%   Processing chunk 4/ 21552       45 chunks/Second(node:2820) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stone' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:2820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2826) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'water' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:2826) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2826) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2838) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'grass' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:2838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
