### ISSUE TITLE
TypeError: Cannot read property 'sand' of null

### ISSUE THREAD

**Issue by umbrellr** [clarkx86/papyrusjs#23]
Extracting...
Attempting to open database...
Success!
Reading database. This can take a couple of seconds up to a couple of minutes.
World reaches from chunks	X:	-43,	Z:	-48	to	X:	+96,	Z:	+82
Processing and rendering 4213 Chunks, which 21959 of them are valid SubChunks...
[--------------------------------] 0%	Processing chunk 3/ 4213	31 chunks/Second(node:31220) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sand' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:31220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[--------------------------------] 0%	Processing chunk 4/ 4213	34 chunks/Second(node:31214) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sand' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:31214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31208) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sand' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:31208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31226) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stone' of null
    at loadTexture (/snapshot/papyrusjs/render/loadTexture.js:25:23)
    at render (/snapshot/papyrusjs/render/renderChunk.js:44:47)
    at /snapshot/papyrusjs/render/renderChunk.js:22:9
    at new Promise (<anonymous>)
    at /snapshot/papyrusjs/render/renderChunk.js:12:12
    at process.<anonymous> (/snapshot/papyrusjs/app.js:360:17)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:31226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by demitt** [comment]
I have almost the same, but "UnhandledPromiseRejectionWarning: TypeError: Cannot read property '**water**' of null"

**Comment by umbrellr** [comment]
> I have almost the same, but "UnhandledPromiseRejectionWarning: TypeError: Cannot read property '**water**' of null"

Using PapyrusCS instead now, I think this project is abandoned..

**Comment by clvrk** [comment]
Hey!
I would also recommend going with PapyrusCS honestly 🙂. I'm mainly focusing on joining forces with @mjungnickel18 and his work with PapyrusCS because it is definitely the main and more stable version.

**EDIT:** I now added a notice about the projects current state to the `README.md`'s head-line!
